version: "3.8"
services:
  webserver:
    build: ../
    container_name: webserver
    env_file:
      - ./webserver.env
    ports:
      - "8010:80"
    links:
      - influxdb
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - internal-network

  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    env_file:
      - ./influx.env
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks: 
      - internal-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "5001:3000"
    user: "0"
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    networks: 
      - internal-network

# persistent data
volumes:
  influxdb_data:
  grafana_data:

networks: 
  internal-network:
    driver: bridge
    name: jipfr_site